- name: Configure dynamic hosts
  hosts: localhost
  tasks:
    - name: Parse data dictionary when defined
      add_host:
        hostname: "{{ item['ipAddress'] }}"
        groups:
          - tag_banner      
      with_items:
        - "{{ json_results.items }}"
      when: "{{ item['ipAddress'] is defined }}"

- name: Configure banners on dynamic hosts
  hosts: tag_banner
  become: true
  roles:
    - config-banner
